name: continuous integration

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branch:
      - "*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: deps cache
        id: cache-go-deps
        uses: actions/cache@v3
        env:
          cache-name: go-deps-cache
        with:
          path: ~/godeps
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashfiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - if: ${{ steps.cache-go-deps.outputs.cache-hit != 'true' }}
        name: list the state of go modules
        continue-on-error: true
        run: go mod graph

      - name: install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@latest

      - name: install dependencies
        run: |
          go mod tidy
          go mod download

      - name: generate templ
        run: templ generate -v

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54.2

      - name: run tests
        run: |
          go test ./...

      - name: run build
        run: |
          go build
